#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=C:\ProgramData\flutter\flutter_windows_1.17.4-stable\flutter"
export "FLUTTER_APPLICATION_PATH=C:\Code\today"
export "FLUTTER_TARGET=lib\main.dart"
export "FLUTTER_BUILD_DIR=build"
export "SYMROOT=${SOURCE_ROOT}/../build\ios"
export "OTHER_LDFLAGS=$(inherited) -framework Flutter"
export "FLUTTER_FRAMEWORK_DIR=C:\ProgramData\flutter\flutter_windows_1.17.4-stable\flutter\bin\cache\artifacts\engine\ios"
export "FLUTTER_BUILD_NAME=0.2.3"
export "FLUTTER_BUILD_NUMBER=6"
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=false"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=.packages"
